# Copyright (C) 2017 NVIDIA Corporation.  All rights reserved.
# Licensed under the CC BY-NC-ND 4.0 license (https://creativecommons.org/licenses/by-nc-nd/4.0/legalcode).
train:
  snapshot_prefix: /misc/vlgscratch2/LecunGroup/laura/im2im/results/double_loop/results # Where do you want to save the outputs
  image_save_iterations: 10
  hyperparameters:
    batch_size: 1
    gen_ab:
      name: COCOResGenSmallK
      ch: 64               # base channel number per layer
      input_dim_a: 3
      input_dim_b: 3
      input_dim_c: 3
      input_dim_d: 3
      n_enc_front_blk: 3
      n_enc_res_blk: 3
      n_enc_shared_blk: 1
      n_gen_shared_blk: 1
      n_gen_res_blk: 3
      n_gen_front_blk: 3
    gen_cd:
      name: COCOResGenSmallK
      ch: 64               # base channel number per layer
      input_dim_a: 3
      input_dim_b: 3
      input_dim_c: 3
      input_dim_d: 3
      n_enc_front_blk: 3
      n_enc_res_blk: 3
      n_enc_shared_blk: 1
      n_gen_shared_blk: 1
      n_gen_res_blk: 3
      n_gen_front_blk: 3
  datasets:
    train_a: # Domain 1 dataset
      channels: 3       # image channel number
      scale: 1.0        # scaling factor for scaling image before processing
      crop_image_size: 128 # crop image size
      class_name: dataset_celeba           # dataset class name
      root: /misc/vlgscratch2/LecunGroup/laura/datasets/celeba/    # dataset folder location
      folder: img_align_128/
      list_name: lists/blond_no_eye_20k.txt
    train_b: # Domain 2 dataset
      channels: 3       # image channel number
      scale: 1.0        # scaling factor for scaling image before processing
      crop_image_size: 128 # crop image size
      class_name: dataset_celeba           # dataset class name
      root: /misc/vlgscratch2/LecunGroup/laura/datasets/celeba/    # dataset folder location
      folder: img_align_128/
      list_name: lists/brunette_no_eye_20k.txt
    train_c: # Domain 2 dataset
      channels: 3       # image channel number
      scale: 1.0        # scaling factor for scaling image before processing
      crop_image_size: 128 # crop image size
      class_name: dataset_celeba           # dataset class name
      root: /misc/vlgscratch2/LecunGroup/laura/datasets/celeba/    # dataset folder location
      folder: img_align_128/
      list_name: lists/smiling_noblond_no_brunette_20k.txt
    train_d: # Domain 2 dataset
      channels: 3       # image channel number
      scale: 1.0        # scaling factor for scaling image before processing
      crop_image_size: 128 # crop image size
      class_name: dataset_celeba           # dataset class name
      root: /misc/vlgscratch2/LecunGroup/laura/datasets/celeba/    # dataset folder location
      folder: img_align_128/
      list_name: lists/nosmiling_noblond_no_brunette_20k.txt
